Manual Respawn + Misc. Changes
Source2ZE/CS2Fixes pull request #134
Opened 2023-12-12 09:07 UTC by EasterLee

2023-12-12 21:42 UTC, EasterLee commented
need help wildcarding setpawn sig for linux

2023-12-16 06:08 UTC, Vauff commented
> need help wildcarding setpawn sig for linux

Doesn't look like it needs anything wildcarded. Don't think that one wildcard in the Windows sig is even needed.

2023-12-16 06:32 UTC, Vauff requested changes

2023-12-16 06:32 UTC, Vauff commented on src/zombiereborn.cpp
> +		g_hTeamT->m_iScore = g_hTeamT->m_iScore() + 1;
You should probably still verify these handles are valid, and log an error/return if not. To save us from debugging crashes later on if we somehow fail to find `cs_team_manager` entities at map start.

2023-12-16 06:32 UTC, Vauff commented on cfg/cs2fixes/cs2fixes.cfg
> +zr_default_winner_team			1		//Which team wins when time ran out, use 1 for draw
I would do the description like `zr_infect_spawn_type` and show all the values. Most people won't know team numbers for T/CT.

2023-12-16 15:42 UTC, Vauff approved these changes

2023-12-16 15:42 UTC, merged