Fixed Binds Issues #204
Source2ZE/CS2Fixes pull request #270
Opened 2024-07-29 17:31 UTC by Geekvcn

Fixed Binds Issues #204

2024-07-29 17:41 UTC, Poggicek requested changes

2024-07-29 17:41 UTC, Poggicek commented on src/cs2fixes.cpp
> +					filtered[filteredLength++] = pszMessage[i];
This code introduces a buffer overflow.

2024-07-29 17:54 UTC, Poggicek commented
from first glance it seems like this would completely break any multi argument commands, even if it didn't do that it still wouldn't properly parse commands, for example `/test 123 "ban reason"` should treat `ban reason` as a single param instead of two which removing all quotes from commands would cause.

2024-07-29 19:48 UTC, Geekvcn commented on src/cs2fixes.cpp
> +					filtered[filteredLength++] = pszMessage[i];
I found another issue where the character at the end of the command is incorrectly removed, such as **'say /hide 300'** becoming **'/hide 30'**. Adding a check for `pszMessage[V_strlen(pszMessage) - 1] == '"'` can fix the issue. Should I submit the code?

2024-09-07 22:13 UTC, Vauff approved these changes

2024-09-07 22:13 UTC, merged